services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: wine-sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Salam123!@
    ports:
      - "1433:1433"
    networks:
      - wine-net
    volumes:
      - mssql_data:/var/opt/mssql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: narmin06/wineapp-backend:latest
    container_name: wine-backend
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:5034
      - ConnectionStrings__DefaultConnection=Server=wine-sql,1433;Database=beveragedb;User Id=sa;Password=Salam123!@;TrustServerCertificate=True;
    ports:
      - "5034:5034"
    networks:
      - wine-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: narmin06/wineapp-frontend:latest
    container_name: wine-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    networks:
      - wine-net

networks:
  wine-net:

volumes:
  mssql_data:
